export const MAPEO = {
 basico_2: {
  "PRACTICA_1A": [
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Apfel]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Ei]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Banane]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Gurke]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Tomate]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Müsli]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Butter]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Salz]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Brötchen (singular)]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Mehl]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Essig]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Pfeffer]",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Fleisch]",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [IEREGZTEM]",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [TKRAM]",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [IEREKCÄB]",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [TKRAMREPUS]"
  ],
  "PRACTICA_1B": [
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [A zum Frühstück]",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [B zum Mittagessen]",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [C zu Kaffee und Kuchen]",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [D zum Abendessen]",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [1]",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [2]",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [3]",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [4]",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [5]"
  ],
  "PRACTICA_1C": [
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Fleisch]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Birne]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Kartoffel]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Käse]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Schinken]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Reis]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der/das Keks]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Olive]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Banane]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Fisch]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Kuchen]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Schokolade]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Pommes frites (Pl.)]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Hähnchen]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Zucker]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Salat]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Würstchen]",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Suppe]"
  ],
  "PRACTICA_2A": [
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [2]",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [3]",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [4]",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [5]",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [6]",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [7]"
  ],
  "PRACTICA_2B": [
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.1]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.2]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.3]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [2.1]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [2.2]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [3.1]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [3.2]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [4.1]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [4.2]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [5.1]",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [5.2 (Brötchen Plural)]",
    "4b. Wählen Sie. [1]",
    "4b. Wählen Sie. [2]",
    "4b. Wählen Sie. [3]",
    "4b. Wählen Sie. [4]",
    "4b. Wählen Sie. [5]",
    "4b. Wählen Sie. [6]",
    "4b. Wählen Sie. [7]",
    "4b. Wählen Sie. [8]",
    "4b. Wählen Sie. [9]"
  ],
  "PRACTICA_2C": [
    "[1. 100 g Käse (Cent)]",
    "[1. 100 g Schinken (Euro)]",
    "[2. 1 kg Bananen (Euro)]",
    "[2. 5 Äpfel (Euro)]",
    "[3. Kaffee (Euro)]",
    "[3. Kuchen (Euro)]"
  ],
  "PRACTICA_3A": [
    "7. Was passt zusammen? [1]",
    "7. Was passt zusammen? [2]",
    "7. Was passt zusammen? [3]",
    "7. Was passt zusammen? [4]",
    "7. Was passt zusammen? [5]",
    "7. Was passt zusammen? [6]",
    "8a. Ergänzen Sie. [1]",
    "8a. Ergänzen Sie. [2]",
    "8a. Ergänzen Sie. [3]",
    "8a. Ergänzen Sie. [4]",
    "8a. Ergänzen Sie. [5]",
    "8a. Ergänzen Sie. [6]",
    "8a. Ergänzen Sie. [7]",
    "8a. Ergänzen Sie. [8]",
    "8a. Ergänzen Sie. [9]",
    "8a. Ergänzen Sie. [10]"
  ],
  "PRACTICA_3B": [
    "9a. Ergänzen Sie [1]",
    "9a. Ergänzen Sie [2]",
    "9a. Ergänzen Sie [3]",
    "9a. Ergänzen Sie [4]",
    "9a. Ergänzen Sie [5]",
    "9a. Ergänzen Sie [6]",
    "9a. Ergänzen Sie [7]",
    "[9b. 2]",
    "[9b. 3]",
    "[9b. 4]",
    "[9b. 5]"
  ],
  "PRACTICA_3C": [
    "10b. Ordnen Sie. [Butter]",
    "10b. Ordnen Sie. [Apfel]",
    "10b. Ordnen Sie. [Sahne]",
    "10b. Ordnen Sie. [Brötchen]",
    "10b. Ordnen Sie. [Birne]",
    "10b. Ordnen Sie. [Käse]",
    "10b. Ordnen Sie. [Kartoffel]",
    "10b. Ordnen Sie. [Banane]",
    "10b. Ordnen Sie. [Salat]",
    "10b. Ordnen Sie. [Gurke]",
    "10b. Ordnen Sie. [Milch]",
    "10b. Ordnen Sie. [Kuchen]",
    "10c. Was passt nicht? [2]",
    "10c. Was passt nicht? [3]",
    "10c. Was passt nicht? [4]",
    "10c. Was passt nicht? [5]",
    "10c. Was passt nicht? [6]",
    "10c. Was passt nicht? [7]",
    "10c. Was passt nicht? [8]"
  ],
  "PRACTICA_4A": [
    "1. Kreuzen Sie an. [1a]",
    "1. Kreuzen Sie an. [1b]",
    "1. Kreuzen Sie an. [1c]",
    "1. Kreuzen Sie an. [2a]",
    "1. Kreuzen Sie an. [2b]",
    "1. Kreuzen Sie an. [2c]",
    "1. Kreuzen Sie an. [3a]",
    "1. Kreuzen Sie an. [3b]",
    "1. Kreuzen Sie an. [3c]",
    "[4a.]",
    "[4b.]",
    "[4c.]"
  ],
  "PRACTICA_4B": [
    "11a. Ordnen Sie zu. [A]",
    "11a. Ordnen Sie zu. [B]",
    "11a. Ordnen Sie zu. [C]",
    "11a. Ordnen Sie zu. [D]",
    "11a. Ordnen Sie zu. [F]"
  ],
  "PRACTICA_4C": [
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8"
  ],
  "PRACTICA_6A": [
    "1a. Der Tag von Lea. [am Morgen (1)]",
    "1a. Der Tag von Lea. [am Morgen (2)]",
    "1a. Der Tag von Lea. [am Vormittag]",
    "1a. Der Tag von Lea. [am Mittag]",
    "1a. Der Tag von Lea. [am Nachmittag]",
    "1a. Der Tag von Lea. [am Abend]",
    "2a. Was passt? [1]",
    "2a. Was passt? [2]",
    "2a. Was passt? [3]",
    "2a. Was passt? [4]",
    "2a. Was passt? [5]",
    "2b. Wählen Sie. [1]",
    "2b. Wählen Sie. [2]",
    "2b. Wählen Sie. [3]",
    "2b. Wählen Sie. [4]",
    "2b. Wählen Sie. [5]",
    "2b. Wählen Sie. [6]",
    "2b. Wählen Sie. [7]"
  ],
  "PRACTICA_6B": [
    "4a. Ordnen Sie zu. [2]",
    "4a. Ordnen Sie zu. [3]",
    "4a. Ordnen Sie zu. [4]",
    "4a. Ordnen Sie zu. [5]",
    "4a. Ordnen Sie zu. [6]",
    "4b. Was passt zusammen? [1]",
    "4b. Was passt zusammen? [2]",
    "4b. Was passt zusammen? [3]",
    "4b. Was passt zusammen? [4]",
    "4b. Was passt zusammen? [5]",
    "4b. Was passt zusammen? [6]"
  ],
  "PRACTICA_6C": [
    "5a. Kreuzen Sie an. [1]",
    "5a. Kreuzen Sie an. [2]",
    "5a. Kreuzen Sie an. [3]",
    "5a. Kreuzen Sie an. [4]",
    "5a. Kreuzen Sie an. [5]",
    "6. Notieren Sie. [Marie besuchen]",
    "6. Notieren Sie. [Tenniskurs]",
    "6. Notieren Sie. [Kino]",
    "6. Notieren Sie. [Pizza essen]"
  ],
  "PRACTICA_7A": [
    "7a. Kreuzen Sie an. [1.1]",
    "7a. Kreuzen Sie an. [1.2]",
    "7a. Kreuzen Sie an. [2.1a]",
    "7a. Kreuzen Sie an. [2.1b]",
    "7a. Kreuzen Sie an. [2.2]",
    "7a. Kreuzen Sie an. [3]",
    "7a. Kreuzen Sie an. [4]",
    "7a. Kreuzen Sie an. [5.1]",
    "7a. Kreuzen Sie an. [5.2]",
    "7b. Ergänzen Sie. [1.1]",
    "7b. Ergänzen Sie. [1.2]",
    "7b. Ergänzen Sie. [2]",
    "7b. Ergänzen Sie. [3.1]",
    "7b. Ergänzen Sie. [3.2]",
    "7b. Ergänzen Sie. [4.1]",
    "7b. Ergänzen Sie. [4.2]",
    "7b. Ergänzen Sie. [5.1]",
    "7b. Ergänzen Sie. [5.2]",
    "7b. Ergänzen Sie. [6.1]",
    "7b. Ergänzen Sie. [6.2]",
    "7b. Ergänzen Sie. [6.3]"
  ],
  "PRACTICA_7B": [
    "8b. Ordnen Sie zu. [1]",
    "8b. Ordnen Sie zu. [2]",
    "8b. Ordnen Sie zu. [3]",
    "8b. Ordnen Sie zu. [4]",
    "8b. Ordnen Sie zu. [5]",
    "8d. Kreuzen Sie an. [1]",
    "8d. Kreuzen Sie an. [2]",
    "8d. Kreuzen Sie an. [3]",
    "8d. Kreuzen Sie an. [4]",
    "8d. Kreuzen Sie an. [5]",
    "8d. Kreuzen Sie an. [6]",
    "8d. Kreuzen Sie an. [7]",
    "8d. Kreuzen Sie an. [8]"
  ],
  "PRACTICA_7C": [
    "8e. Ergänzen Sie. [1]",
    "8e. Ergänzen Sie. [2]",
    "8e. Ergänzen Sie. [3]",
    "8e. Ergänzen Sie. [4]",
    "8e. Ergänzen Sie. [5]",
    "8e. Ergänzen Sie. [6]",
    "8e. Ergänzen Sie. [7]",
    "8e. Ergänzen Sie. [8]",
    "9a. Ordnen Sie. [Geschwister]",
    "9a. Ordnen Sie. [arbeiten]",
    "9a. Ordnen Sie. [fahren]",
    "9a. Ordnen Sie. [Mutter]",
    "9a. Ordnen Sie. [Kalender]",
    "9a. Ordnen Sie. [fragen]",
    "9a. Ordnen Sie. [frühstücken]",
    "9a. Ordnen Sie. [Kinder]"
  ],
  "PRACTICA_8A": [
    "9b. Kreuzen Sie an. [1]",
    "9b. Kreuzen Sie an. [2]",
    "9b. Kreuzen Sie an. [3]",
    "9b. Kreuzen Sie an. [4]",
    "9b. Kreuzen Sie an. [5]",
    "9b. Kreuzen Sie an. [6.1]",
    "9b. Kreuzen Sie an. [6.2]",
    "11a. Ergänzen Sie. [1]",
    "11a. Ergänzen Sie. [2]",
    "11a. Ergänzen Sie. [3]",
    "11a. Ergänzen Sie. [4]",
    "11c. Ergänzen Sie. [1]",
    "11c. Ergänzen Sie. [2]",
    "11c. Ergänzen Sie. [3]",
    "11c. Ergänzen Sie. [4]",
    "11c. Ergänzen Sie. [5]",
    "11c. Ergänzen Sie. [6]",
    "11c. Ergänzen Sie. [7]",
    "11c. Ergänzen Sie. [8]"
  ],
  "PRACTICA_8B": [
    "12a. Ergänzen Sie. [1]",
    "12a. Ergänzen Sie. [2]",
    "12a. Ergänzen Sie. [3]",
    "12a. Ergänzen Sie. [4]",
    "12a. Ergänzen Sie. [5]",
    "12a. Ergänzen Sie. [6]",
    "12a. Ergänzen Sie. [7]",
    "12a. Ergänzen Sie. [8]",
    "13ab. Notieren Sie. [A]",
    "13ab. Notieren Sie. [B]",
    "13ab. Notieren Sie. [C]",
    "13ab. Notieren Sie. [D]",
    "13ab. Notieren Sie. [E]",
    "13ab. Notieren Sie. [F]",
    "13ab. Notieren Sie. [G]",
    "13ab. Notieren Sie. [H]",
    "13ab. Notieren Sie. [I]",
    "13ab. Notieren Sie. [J]"
  ]
 },
 basico_4: {
    "PRACTICA_1A": [
    "1b. Was machen Annikas Freunde und Freundinnen? [Tim und Katharina]",
    "1b. Was machen Annikas Freunde und Freundinnen? [Jan möchte]",
    "1b. Was machen Annikas Freunde und Freundinnen? [Laura]",
    "1b. Was machen Annikas Freunde und Freundinnen? [Alina und Kim wollen]",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [In der Arbeit habe ich viel Stress.]",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich gehe nicht gern ins Fitness-Studio.]",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich gehe jede Woche schwimmen.]",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich esse gern mit Freunden.]",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich esse gesund und es geht mir gut.]"
  ],
  "PRACTICA_1B": [
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [1]",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [2]",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [3]",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [4]",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [5]"
  ],
  "PRACTICA_1C": [
    "[aufstehen - du-Form]",
    "[Wasser trinken - du-Form]",
    "[Wasser trinken - ihr-Form]",
    "[Salat essen - du-Form]",
    "[Salat essen - Sie-Form]",
    "[auch mitmachen - ihr-Form]",
    "[auch mitmachen - Sie-Form]",
    "[einen Ball holen - du-Form]",
    "[einen Ball holen - ihr-Form]",
    "[schnell laufen - du-Form]",
    "[schnell laufen - Sie-Form]",
    "[aktiv sein - ihr-Form]",
    "[aktiv sein - Sie-Form]"
  ],
  "PRACTICA_2A": [
    "3c. Was sagen die Leute? [A]",
    "3c. Was sagen die Leute? [B]",
    "3c. Was sagen die Leute? [C1]",
    "3c. Was sagen die Leute? [C2]",
    "3c. Was sagen die Leute? [D1]",
    "3c. Was sagen die Leute? [D2]",
    "3c. Was sagen die Leute? [E]",
    "3c. Was sagen die Leute? [F]",
    "[4. Formulieren Sie im Imperativ mit du. Beispiel: täglich in den Park gehen → Geh täglich in den Park! 4.1. den Fernseher ausmachen (ihr)]",
    "[4.2. nicht so viel arbeiten (du)]",
    "[4.3. nicht so viel Kaffee trinken (du)]",
    "[4.4 für die Prüfung lernen (ihr)]"
  ],
  "PRACTICA_2B": [
    "[4.5. immer wieder eine Pause machen (du)]",
    "[4.6. vom Sofa aufstehen (ihr)]",
    "[4.7. mit der Chefin sprechen (du)]",
    "[4.8. aktiv sein (ihr)]",
    "[4.9. gemeinsam kochen (ihr)]",
    "[5. Hören Sie und notieren Sie die Zahlen und Maße. Person 2. ___ Kilo]",
    "[Person 3. ___ (Zentimeter!!)]",
    "[Person 4. ___ Kilo]",
    "[Person 5. ___ (Jahre)]"
  ],
  "PRACTICA_2C": [
    "6c. Was passt wo? Notieren Sie. [2. riechen]",
    "6c. Was passt wo? Notieren Sie. [3. hören]",
    "6c. Was passt wo? Notieren Sie. [4. sehen]",
    "7a. Markieren Sie. [2]",
    "7a. Markieren Sie. [3]",
    "7a. Markieren Sie. [4]",
    "7a. Markieren Sie. [5]",
    "7a. Markieren Sie. [6]",
    "7a. Markieren Sie. [7]",
    "7a. Markieren Sie. [8]",
    "7a. Markieren Sie. [9]",
    "7a. Markieren Sie. [10]",
    "7a. Markieren Sie. [11]",
    "7a. Markieren Sie. [12]"
  ],
  "PRACTICA_3A": [
    "8c. Ergänzen Sie die Tabelle. [ich]",
    "8c. Ergänzen Sie die Tabelle. [du]",
    "8c. Ergänzen Sie die Tabelle. [ihr]",
    "8c. Ergänzen Sie die Tabelle. [sie/Sie]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [1]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [2]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [3]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [4]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [5]",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [6]"
  ],
  "PRACTICA_3B": [
    "[8e. 2]",
    "[8e. 3]",
    "[8e. 4]",
    "[8e. 5]",
    "10. Was sagt der Arzt und Patientin? [2]",
    "10. Was sagt der Arzt und Patientin? [3]",
    "10. Was sagt der Arzt und Patientin? [4]",
    "10. Was sagt der Arzt und Patientin? [5]",
    "10. Was sagt der Arzt und Patientin? [6]",
    "10. Was sagt der Arzt und Patientin? [7]",
    "10. Was sagt der Arzt und Patientin? [8]",
    "10. Was sagt der Arzt und Patientin? [9]",
    "10. Was sagt der Arzt und Patientin? [10]",
    "10. Was sagt der Arzt und Patientin? [11]",
    "10. Was sagt der Arzt und Patientin? [12]",
    "10. Was sagt der Arzt und Patientin? [13]",
    "10. Was sagt der Arzt und Patientin? [14]",
    "10. Was sagt der Arzt und Patientin? [15]"
  ],
  "PRACTICA_3C": [
    "10c. Was passt nicht? [1]",
    "10c. Was passt nicht? [2]",
    "10c. Was passt nicht? [3]",
    "10c. Was passt nicht? [4]",
    "10c. Was passt nicht? [5]",
    "10e. Ergänzen Sie. [1]",
    "10e. Ergänzen Sie. [2]",
    "10e. Ergänzen Sie. [3]",
    "10e. Ergänzen Sie. [4]",
    "10e. Ergänzen Sie. [5]",
    "10e. Ergänzen Sie. [6]",
    "10e. Ergänzen Sie. [7]"
  ],
  "PRACTICA_4A": [
    "10f. Ergänzen Sie. [1]",
    "10f. Ergänzen Sie. [2]",
    "10f. Ergänzen Sie. [3]",
    "10f. Ergänzen Sie. [4]",
    "10f. Ergänzen Sie. [5]",
    "10f. Ergänzen Sie. [6]",
    "10f. Ergänzen Sie. [7]",
    "10f. Ergänzen Sie. [8]"
  ],
  "PRACTICA_4B": [
    "11a. Ordnen Sie zu. [1]",
    "11a. Ordnen Sie zu. [2]",
    "11a. Ordnen Sie zu. [3]",
    "11a. Ordnen Sie zu. [4]",
    "11a. Ordnen Sie zu. [5]",
    "11a. Ordnen Sie zu. [6]",
    "11a. Ordnen Sie zu. [7]",
    "11b. Ordnen Sie zu. [1]",
    "11b. Ordnen Sie zu. [2]",
    "11b. Ordnen Sie zu. [3]",
    "11b. Ordnen Sie zu. [4]",
    "11b. Ordnen Sie zu. [5]"
  ],
  "PRACTICA_4C": [
    "13a. Komposita. [2]",
    "13a. Komposita. [3]",
    "13a. Komposita. [4]",
    "13a. Komposita. [5]",
    "13a. Komposita. [6]",
    "13a. Komposita. [7]",
    "13a. Komposita. [8]",
    "13c. Kreuzen Sie an. [A]",
    "13c. Kreuzen Sie an. [B]"
  ],
  "PRACTICA_6A": [
    "1a. Was passt zusammen? [1]",
    "1a. Was passt zusammen? [2]",
    "1a. Was passt zusammen? [3]",
    "1a. Was passt zusammen? [4]",
    "1a. Was passt zusammen? [5]",
    "1a. Was passt zusammen? [6]",
    "1a. Was passt zusammen? [7]",
    "1a. Was passt zusammen? [8]",
    "1a. Was passt zusammen? [9]",
    "1a. Was passt zusammen? [10]",
    "1a. Was passt zusammen? [11]",
    "1a. Was passt zusammen? [12]",
    "1a. Was passt zusammen? [13]",
    "1a. Was passt zusammen? [14]",
    "1a. Was passt zusammen? [15]",
    "1c. Wie heißen die Zimmer? [A]",
    "1c. Wie heißen die Zimmer? [B]",
    "1c. Wie heißen die Zimmer? [C]",
    "1c. Wie heißen die Zimmer? [D]",
    "1c. Wie heißen die Zimmer? [E]"
  ],
  "PRACTICA_6B": [
    "2. Lesen Sie. [1]",
    "2. Lesen Sie. [2]",
    "2. Lesen Sie. [3]",
    "2. Lesen Sie. [4]"
  ],
  "PRACTICA_6C": [
    "3a. Wie ist die Wohnung? [1]",
    "3a. Wie ist die Wohnung? [2]",
    "3a. Wie ist die Wohnung? [3]",
    "3a. Wie ist die Wohnung? [4]",
    "3b. Lesen Sie. [1]",
    "3b. Lesen Sie. [2]",
    "3b. Lesen Sie. [3]",
    "3b. Lesen Sie. [4]"
  ],
  "PRACTICA_7A": [
    "4a. Hören Sie. [Waschmaschine]",
    "4a. Hören Sie. [Regale]",
    "4a. Hören Sie. [Schrank]",
    "4a. Hören Sie. [Betten]",
    "4a. Hören Sie. [Esstisch]",
    "4a. Hören Sie. [Sofa]",
    "4c. Kreuzen Sie an. [1]",
    "4c. Kreuzen Sie an. [2]",
    "4c. Kreuzen Sie an. [3]",
    "4c. Kreuzen Sie an. [4]",
    "4c. Kreuzen Sie an. [5]",
    "4c. Kreuzen Sie an. [6]"
  ],
  "PRACTICA_7B": [
    "5a. Hören Sie. [1]",
    "5a. Hören Sie. [2]",
    "5a. Hören Sie. [3]",
    "5a. Hören Sie. [4]",
    "5b. Sortieren Sie. [ihr]",
    "5b. Sortieren Sie. [eine]",
    "5b. Sortieren Sie. [also]",
    "5b. Sortieren Sie. [vielen]",
    "5b. Sortieren Sie. [liebe]",
    "5b. Sortieren Sie. [danke]",
    "5b. Sortieren Sie. [feiert]",
    "5b. Sortieren Sie. [hallo]",
    "5b. Sortieren Sie. [ich kann]",
    "5b. Sortieren Sie. [aber]",
    "5b. Sortieren Sie. [ich muss]"
  ],
  "PRACTICA_7C": [
    "6a. Ergänzen Sie [1]",
    "6a. Ergänzen Sie [2]",
    "6a. Ergänzen Sie [3]",
    "6a. Ergänzen Sie [4]",
    "6a. Ergänzen Sie [5]",
    "6a. Ergänzen Sie [6]",
    "6a. Ergänzen Sie [7]",
    "6a. Ergänzen Sie [8]",
    "6a. Ergänzen Sie [9]",
    "6b. Hören Sie. [das Besteck]",
    "6b. Hören Sie. [die Gläser]",
    "6b. Hören Sie. [die Flasche]",
    "6b. Hören Sie. [die Servietten]"
  ],
  "PRACTICA_8A": [
    "8a. Kreuzen Sie an. [1]",
    "8a. Kreuzen Sie an. [2]",
    "8a. Kreuzen Sie an. [3]",
    "8a. Kreuzen Sie an. [4]",
    "8a. Kreuzen Sie an. [5]",
    "8a. Kreuzen Sie an. [6]",
    "9b. Hören Sie. [A]",
    "9b. Hören Sie. [B]",
    "9b. Hören Sie. [C]"
  ],
  "PRACTICA_8B": [
    "12a. Lesen Sie. [Wählen Sie aus.]",
    "12b. Kreuzen Sie an. [2]",
    "12b. Kreuzen Sie an. [3]",
    "12b. Kreuzen Sie an. [4]",
    "12b. Kreuzen Sie an. [5]",
    "12b. Kreuzen Sie an. [6]",
    "12b. Kreuzen Sie an. [7]"
  ]
 }
};
