export const MISSION_MAP: Record<string, Record<string, string>> = {
  basico_2: {
    "1a": "PRACTICA_1A",
    "1b": "PRACTICA_1B",
    "1c": "PRACTICA_1C",
    "2a": "PRACTICA_2A",
    "2b": "PRACTICA_2B",
    "2c": "PRACTICA_2C",
    "3a": "PRACTICA_3A",
    "3b": "PRACTICA_3B",
    "3c": "PRACTICA_3C",
    "4a": "PRACTICA_4A",
    "4b": "PRACTICA_4B",
    "4c": "PRACTICA_4C",
    "6a": "PRACTICA_6A",
    "6b": "PRACTICA_6B",
    "6c": "PRACTICA_6C",
    "7a": "PRACTICA_7A",
    "7b": "PRACTICA_7B",
    "7c": "PRACTICA_7C",
    "8a": "PRACTICA_8A",
    "8b": "PRACTICA_8B",
  },
  basico_4: {
    "1a": "PRACTICA_1A",
    "1b": "PRACTICA_1B",
    "1c": "PRACTICA_1C",
    "2a": "PRACTICA_2A",
    "2b": "PRACTICA_2B",
    "2c": "PRACTICA_2C",
    "3a": "PRACTICA_3A",
    "3b": "PRACTICA_3B",
    "3c": "PRACTICA_3C",
    "4a": "PRACTICA_4A",
    "4b": "PRACTICA_4B",
    "4c": "PRACTICA_4C",
    "6a": "PRACTICA_6A",
    "6b": "PRACTICA_6B",
    "6c": "PRACTICA_6C",
    "7a": "PRACTICA_7A",
    "7b": "PRACTICA_7B",
    "7c": "PRACTICA_7C",
    "8a": "PRACTICA_8A",
    "8b": "PRACTICA_8B",
  },
};