// AUTOGENERADO — no editar manualmente
// Regenerar: npx tsx scripts/build-respuestas-auto.ts

export const RESPUESTAS: Record<string, Record<string, string>> = {
  "basico_2": {
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Apfel]": "kommt nicht in den Kühlschrank, der",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Ei]": "kommt in den Kühlschrank, das",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Banane]": "kommt nicht in den Kühlschrank, die",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Gurke]": "kommt nicht in den Kühlschrank, die",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Tomate]": "kommt nicht in den Kühlschrank, die",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Müsli]": "kommt nicht in den Kühlschrank, das",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Butter]": "kommt in den Kühlschrank, die",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Salz]": "kommt nicht in den Kühlschrank, das",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Brötchen (singular)]": "kommt nicht in den Kühlschrank, das",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Mehl]": "kommt nicht in den Kühlschrank, das",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Essig]": "kommt nicht in den Kühlschrank, der",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Pfeffer]": "kommt nicht in den Kühlschrank, der",
    "1a. Was kommt in den Kühlschrank, was nicht? Ordnen Sie zu. [Fleisch]": "kommt in den Kühlschrank, das",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [IEREGZTEM]": "die",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [TKRAM]": "der",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [IEREKCÄB]": "die",
    "2. Wie heißen die Geschäfte? Notieren Sie die Wörter mit Artikel [TKRAMREPUS]": "der",
    "Ordnen Sie: IEREGZTEM": "Metzgerei",
    "Ordnen Sie: TKRAM": "Markt",
    "Ordnen Sie: IEREKCÄB": "Bäckerei",
    "Ordnen Sie: TKRAMREPUS": "Supermarkt",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [A zum Frühstück]": "Nachricht 3",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [B zum Mittagessen]": "Nachricht 4",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [C zu Kaffee und Kuchen]": "Nachricht 1",
    "3a. Eine Einladung. Hören Sie. Welche Nachricht passt? Notieren Sie. [D zum Abendessen]": "Nachricht 2",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [1]": "E",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [2]": "D",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [3]": "C",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [4]": "A",
    "3b. Die Grillparty. Ergänzen Sie den Dialog. Ordnen Sie zu. [5]": "B",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Fleisch]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Birne]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Kartoffel]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Käse]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Schinken]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Reis]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der/das Keks]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Olive]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Banane]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Fisch]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Kuchen]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Schokolade]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Pommes frites (Pl.)]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Hähnchen]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Zucker]": "süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [der Salat]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [das Würstchen]": "nicht süß",
    "3c. Wie schmeckt das? Ordnen Sie die Lebensmittel zu. [die Suppe]": "nicht süß",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [2]": "das, Fleisch",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [3]": "den, Apfelkuchen",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [4]": "das, Obst",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [5]": "das, Wasser",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [6]": "die, Kartoffeln",
    "3d. Ergänzen Sie die Nachricht mit den Nomen und dem bestimmten Artikel. [7]": "die, Würtschen (Plural)",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.1]": "eine",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.2]": "eine",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [1.3]": "-",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [2.1]": "ein",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [2.2]": "eine",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [3.1]": "einen",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [3.2]": "ein",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [4.1]": "eine",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [4.2]": "einen",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [5.1]": "eine",
    "4a. Ergänzen Sie ein und - in der richtigen Form. [5.2 (Brötchen Plural)]": "-",
    "4b. Wählen Sie. [1]": "eine Party",
    "4b. Wählen Sie. [2]": "einen Kuchen",
    "4b. Wählen Sie. [3]": "einen Salat",
    "4b. Wählen Sie. [4]": "die Getränke",
    "4b. Wählen Sie. [5]": "die Brötchen",
    "4b. Wählen Sie. [6]": "keinen Salat",
    "4b. Wählen Sie. [7]": "einen Kuchen",
    "4b. Wählen Sie. [8]": "einen Fisch",
    "4b. Wählen Sie. [9]": "den Fisch",
    "1. 100 g Käse (Cent)": "99",
    "1. 100 g Schinken (Euro)": "1,09",
    "2. 1 kg Bananen (Euro)": "1,70",
    "2. 5 Äpfel (Euro)": "1,30",
    "3. Kaffee (Euro)": "1,50",
    "3. Kuchen (Euro)": "1,80",
    "7. Was passt zusammen? [1]": "F",
    "7. Was passt zusammen? [2]": "C",
    "7. Was passt zusammen? [3]": "E",
    "7. Was passt zusammen? [4]": "D",
    "7. Was passt zusammen? [5]": "A",
    "7. Was passt zusammen? [6]": "B",
    "8a. Ergänzen Sie. [1]": "möchten",
    "8a. Ergänzen Sie. [2]": "möchte",
    "8a. Ergänzen Sie. [3]": "möchte",
    "8a. Ergänzen Sie. [4]": "möchten",
    "8a. Ergänzen Sie. [5]": "möchte",
    "8a. Ergänzen Sie. [6]": "möchten",
    "8a. Ergänzen Sie. [7]": "möchtest",
    "8a. Ergänzen Sie. [8]": "möchten",
    "8a. Ergänzen Sie. [9]": "möchten",
    "8a. Ergänzen Sie. [10]": "möchten",
    "9a. Ergänzen Sie [1]": "mag",
    "9a. Ergänzen Sie [2]": "mögen",
    "9a. Ergänzen Sie [3]": "mag",
    "9a. Ergänzen Sie [4]": "mögen",
    "9a. Ergänzen Sie [5]": "mögt",
    "9a. Ergänzen Sie [6]": "magst",
    "9a. Ergänzen Sie [7]": "mögen",
    "9b. 2": "Ich trinke einen Milchkaffee zum Frühstück.",
    "9b. 3": "Vormittags trinke ich Tee.",
    "9b. 4": "Mittags esse ich Nudeln mit Gemüse.",
    "9b. 5": "Brot und Käse esse ich abends.",
    "10b. Ordnen Sie. [Butter]": "die, Milchprodukte",
    "10b. Ordnen Sie. [Apfel]": "der, Obst",
    "10b. Ordnen Sie. [Sahne]": "die, Milchprodukte",
    "10b. Ordnen Sie. [Brötchen]": "das, Backwaren",
    "10b. Ordnen Sie. [Birne]": "die, Obst",
    "10b. Ordnen Sie. [Käse]": "der, Milchprodukte",
    "10b. Ordnen Sie. [Kartoffel]": "die, Gemüse",
    "10b. Ordnen Sie. [Banane]": "die, Obst",
    "10b. Ordnen Sie. [Salat]": "der, Gemüse",
    "10b. Ordnen Sie. [Gurke]": "die, Gemüse",
    "10b. Ordnen Sie. [Milch]": "die, Milchprodukte",
    "10b. Ordnen Sie. [Kuchen]": "der, Backwaren",
    "10c. Was passt nicht? [2]": "4",
    "10c. Was passt nicht? [3]": "1",
    "10c. Was passt nicht? [4]": "4",
    "10c. Was passt nicht? [5]": "4",
    "10c. Was passt nicht? [6]": "2",
    "10c. Was passt nicht? [7]": "3",
    "10c. Was passt nicht? [8]": "1",
    "1. Kreuzen Sie an. [1a]": "4",
    "1. Kreuzen Sie an. [1b]": "2",
    "1. Kreuzen Sie an. [1c]": "4",
    "1. Kreuzen Sie an. [2a]": "2",
    "1. Kreuzen Sie an. [2b]": "2",
    "1. Kreuzen Sie an. [2c]": "3",
    "1. Kreuzen Sie an. [3a]": "4",
    "1. Kreuzen Sie an. [3b]": "3",
    "1. Kreuzen Sie an. [3c]": "2",
    "4a.": "Er mag sehr den süßen Honig.",
    "4b.": "Du möchtest den knusprigen Apfel essen.",
    "4c.": "Ich möchte die Mango-Chili-Marmelade probieren.",
    "11a. Ordnen Sie zu. [A]": "3",
    "11a. Ordnen Sie zu. [B]": "2",
    "11a. Ordnen Sie zu. [C]": "6",
    "11a. Ordnen Sie zu. [D]": "5",
    "11a. Ordnen Sie zu. [F]": "4",
    "1.1": "Zum Frühstück esse ich ein Brötchen mit Butter.",
    "1.2": "Ich trinke morgens einen Kaffee.",
    "1.3": "Mittags essen wir Reis mit Gemüse.",
    "1.4": "Am Abend esse ich einen Salat.",
    "1.5": "Wir trinken nachmittags Orangensaft.",
    "1.6": "Abends esse ich Brot und Käse.",
    "1.7": "Am Wochenende koche ich Nudeln.",
    "1.8": "Zum Mittagessen trinke ich Wasser.",
    "1a. Der Tag von Lea. [am Morgen (1)]": "duschen",
    "1a. Der Tag von Lea. [am Morgen (2)]": "frühstücken",
    "1a. Der Tag von Lea. [am Vormittag]": "lernen",
    "1a. Der Tag von Lea. [am Mittag]": "essen",
    "1a. Der Tag von Lea. [am Nachmittag]": "reden",
    "1a. Der Tag von Lea. [am Abend]": "schlafen gehen",
    "2a. Was passt? [1]": "lesen",
    "2a. Was passt? [2]": "spielen",
    "2a. Was passt? [3]": "treffen",
    "2a. Was passt? [4]": "essen",
    "2a. Was passt? [5]": "gehen",
    "2b. Wählen Sie. [1]": "isst",
    "2b. Wählen Sie. [2]": "spielt",
    "2b. Wählen Sie. [3]": "trifft",
    "2b. Wählen Sie. [4]": "geht",
    "2b. Wählen Sie. [5]": "schläft",
    "2b. Wählen Sie. [6]": "lernt",
    "2b. Wählen Sie. [7]": "besucht",
    "4a. Ordnen Sie zu. [2]": "9:00-12:00",
    "4a. Ordnen Sie zu. [3]": "12:00-14:00",
    "4a. Ordnen Sie zu. [4]": "14:00-18:00",
    "4a. Ordnen Sie zu. [5]": "18:00-22:00",
    "4a. Ordnen Sie zu. [6]": "22:00-6:00",
    "4b. Was passt zusammen? [1]": "E",
    "4b. Was passt zusammen? [2]": "A",
    "4b. Was passt zusammen? [3]": "F",
    "4b. Was passt zusammen? [4]": "B",
    "4b. Was passt zusammen? [5]": "C",
    "4b. Was passt zusammen? [6]": "D",
    "5a. Kreuzen Sie an. [1]": "a",
    "5a. Kreuzen Sie an. [2]": "b",
    "5a. Kreuzen Sie an. [3]": "b",
    "5a. Kreuzen Sie an. [4]": "a",
    "5a. Kreuzen Sie an. [5]": "a",
    "6. Notieren Sie. [Marie besuchen]": "um halb eins",
    "6. Notieren Sie. [Tenniskurs]": "um vier Uhr",
    "6. Notieren Sie. [Kino]": "um Viertel vor acht",
    "6. Notieren Sie. [Pizza essen]": "um Viertel nach sechs",
    "7a. Kreuzen Sie an. [1.1]": "am",
    "7a. Kreuzen Sie an. [1.2]": "um",
    "7a. Kreuzen Sie an. [2.1a]": "am",
    "7a. Kreuzen Sie an. [2.1b]": "um",
    "7a. Kreuzen Sie an. [2.2]": "am",
    "7a. Kreuzen Sie an. [3]": "am",
    "7a. Kreuzen Sie an. [4]": "um",
    "7a. Kreuzen Sie an. [5.1]": "am",
    "7a. Kreuzen Sie an. [5.2]": "um",
    "7b. Ergänzen Sie. [1.1]": "von",
    "7b. Ergänzen Sie. [1.2]": "bis",
    "7b. Ergänzen Sie. [2]": "am",
    "7b. Ergänzen Sie. [3.1]": "von",
    "7b. Ergänzen Sie. [3.2]": "bis",
    "7b. Ergänzen Sie. [4.1]": "am",
    "7b. Ergänzen Sie. [4.2]": "um",
    "7b. Ergänzen Sie. [5.1]": "am",
    "7b. Ergänzen Sie. [5.2]": "um",
    "7b. Ergänzen Sie. [6.1]": "am",
    "7b. Ergänzen Sie. [6.2]": "von",
    "7b. Ergänzen Sie. [6.3]": "bis",
    "8b. Ordnen Sie zu. [1]": "C",
    "8b. Ordnen Sie zu. [2]": "E",
    "8b. Ordnen Sie zu. [3]": "B",
    "8b. Ordnen Sie zu. [4]": "A",
    "8b. Ordnen Sie zu. [5]": "D",
    "8d. Kreuzen Sie an. [1]": "meine",
    "8d. Kreuzen Sie an. [2]": "meine",
    "8d. Kreuzen Sie an. [3]": "meinen",
    "8d. Kreuzen Sie an. [4]": "meinen",
    "8d. Kreuzen Sie an. [5]": "meine",
    "8d. Kreuzen Sie an. [6]": "meine",
    "8d. Kreuzen Sie an. [7]": "meine",
    "8d. Kreuzen Sie an. [8]": "meine",
    "8e. Ergänzen Sie. [1]": "mein",
    "8e. Ergänzen Sie. [2]": "mein",
    "8e. Ergänzen Sie. [3]": "meine",
    "8e. Ergänzen Sie. [4]": "meine",
    "8e. Ergänzen Sie. [5]": "meine",
    "8e. Ergänzen Sie. [6]": "meine",
    "8e. Ergänzen Sie. [7]": "meine",
    "8e. Ergänzen Sie. [8]": "meinen",
    "9a. Ordnen Sie. [Geschwister]": "a",
    "9a. Ordnen Sie. [arbeiten]": "a",
    "9a. Ordnen Sie. [fahren]": "r",
    "9a. Ordnen Sie. [Mutter]": "a",
    "9a. Ordnen Sie. [Kalender]": "a",
    "9a. Ordnen Sie. [fragen]": "r",
    "9a. Ordnen Sie. [frühstücken]": "r",
    "9a. Ordnen Sie. [Kinder]": "a",
    "9b. Kreuzen Sie an. [1]": "a",
    "9b. Kreuzen Sie an. [2]": "a",
    "9b. Kreuzen Sie an. [3]": "a",
    "9b. Kreuzen Sie an. [4]": "a",
    "9b. Kreuzen Sie an. [5]": "b",
    "9b. Kreuzen Sie an. [6.1]": "a",
    "9b. Kreuzen Sie an. [6.2]": "b",
    "11a. Ergänzen Sie. [1]": "will",
    "11a. Ergänzen Sie. [2]": "kannst",
    "11a. Ergänzen Sie. [3]": "muss",
    "11a. Ergänzen Sie. [4]": "wollen",
    "11c. Ergänzen Sie. [1]": "muss",
    "11c. Ergänzen Sie. [2]": "will",
    "11c. Ergänzen Sie. [3]": "können",
    "11c. Ergänzen Sie. [4]": "muss",
    "11c. Ergänzen Sie. [5]": "wollen",
    "11c. Ergänzen Sie. [6]": "willst",
    "11c. Ergänzen Sie. [7]": "kann",
    "11c. Ergänzen Sie. [8]": "will",
    "12a. Ergänzen Sie. [1]": "morgen",
    "12a. Ergänzen Sie. [2]": "Zeit",
    "12a. Ergänzen Sie. [3]": "leid",
    "12a. Ergänzen Sie. [4]": "zum Arzt",
    "12a. Ergänzen Sie. [5]": "Schade",
    "12a. Ergänzen Sie. [6]": "geht",
    "12a. Ergänzen Sie. [7]": "ins Café",
    "12a. Ergänzen Sie. [8]": "Idee",
    "13ab. Notieren Sie. [A]": "8",
    "13ab. Notieren Sie. [B]": "A",
    "13ab. Notieren Sie. [C]": "W, 10",
    "13ab. Notieren Sie. [D]": "A, 3",
    "13ab. Notieren Sie. [E]": "A, 5",
    "13ab. Notieren Sie. [F]": "W, 6",
    "13ab. Notieren Sie. [G]": "W, 4",
    "13ab. Notieren Sie. [H]": "A, 9",
    "13ab. Notieren Sie. [I]": "A, 7",
    "13ab. Notieren Sie. [J]": "W, 2"
  },
  "basico_4": {
    "1b. Was machen Annikas Freunde und Freundinnen? [Tim und Katharina]": "mehr Sport machen",
    "1b. Was machen Annikas Freunde und Freundinnen? [Jan möchte]": "Gesund frühstücken",
    "1b. Was machen Annikas Freunde und Freundinnen? [Laura]": "geht früh schlafen",
    "1b. Was machen Annikas Freunde und Freundinnen? [Alina und Kim wollen]": "wenig Süßigkeiten essen",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [In der Arbeit habe ich viel Stress.]": "Hannah",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich gehe nicht gern ins Fitness-Studio.]": "Tom",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich gehe jede Woche schwimmen.]": "Hannah",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich esse gern mit Freunden.]": "Hannah",
    "1c. Lesen Sie die Beiträge aus dem Forum und kreuzen Sie an: Wer schreibt was? [Ich esse gesund und es geht mir gut.]": "Tom",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [1]": "C",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [2]": "E",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [3]": "A",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [4]": "B",
    "2a. Was sagen die Freunden von Annika? Ordnen Sie zu. [5]": "D",
    "aufstehen - du-Form": "Steh auf!",
    "Wasser trinken - du-Form": "Trink Wasser!",
    "Wasser trinken - ihr-Form": "Trinkt Wasser!",
    "Salat essen - du-Form": "Iss Salat!",
    "Salat essen - Sie-Form": "Essen Sie Salat!",
    "auch mitmachen - ihr-Form": "Macht auch mit!",
    "auch mitmachen - Sie-Form": "Machen Sie auch mit!",
    "einen Ball holen - du-Form": "Hol einen Ball!",
    "einen Ball holen - ihr-Form": "Holt einen Ball!",
    "schnell laufen - du-Form": "Lauf schnell!",
    "schnell laufen - Sie-Form": "Laufen Sie schnell!",
    "aktiv sein - ihr-Form": "Seid aktiv!",
    "aktiv sein - Sie-Form": "Seien Sie aktiv!",
    "3c. Was sagen die Leute? [A]": "Iss-, -0",
    "3c. Was sagen die Leute? [B]": "Mach- zu, -0",
    "3c. Was sagen die Leute? [C1]": "Sieh- fern, -0",
    "3c. Was sagen die Leute? [C2]": "Sei-, -0",
    "3c. Was sagen die Leute? [D1]": "Lern-, -0",
    "3c. Was sagen die Leute? [D2]": "Geh-, -0",
    "3c. Was sagen die Leute? [E]": "Lauf-, -t",
    "3c. Was sagen die Leute? [F]": "Steh- auf, -t",
    "4.5. immer wieder eine Pause machen (du)": "Mach immer wieder eine Pause!",
    "4.6. vom Sofa aufstehen (ihr)": "Steht vom Sofa auf!",
    "4.7. mit der Chefin sprechen (du)": "Sprich mit der Chefin!",
    "4.8. aktiv sein (ihr)": "Seid aktiv!",
    "4.9. gemeinsam kochen (ihr)": "Kocht gemeinsam!",
    "5. Hören Sie und notieren Sie die Zahlen und Maße. Person 2. ___ Kilo": "85",
    "5. Hören Sie und notieren Sie die Zahlen und Maße. Person 3. ___ (Zentimeter!!)": "178",
    "5. Hören Sie und notieren Sie die Zahlen und Maße. Person 4. ___ Kilo": "64",
    "5. Hören Sie und notieren Sie die Zahlen und Maße. Person 5. ___ (Jahre)": "48",
    "6c. Was passt wo? Notieren Sie. [2. riechen]": "die Nase",
    "6c. Was passt wo? Notieren Sie. [3. hören]": "das Ohr",
    "6c. Was passt wo? Notieren Sie. [4. sehen]": "das Auge",
    "7a. Markieren Sie. [2]": "t",
    "7a. Markieren Sie. [3]": "g",
    "7a. Markieren Sie. [4]": "b",
    "7a. Markieren Sie. [5]": "d",
    "7a. Markieren Sie. [6]": "g",
    "7a. Markieren Sie. [7]": "p",
    "7a. Markieren Sie. [8]": "t",
    "7a. Markieren Sie. [9]": "g",
    "7a. Markieren Sie. [10]": "b",
    "7a. Markieren Sie. [11]": "t",
    "7a. Markieren Sie. [12]": "k",
    "8c. Ergänzen Sie die Tabelle. [ich]": "soll",
    "8c. Ergänzen Sie die Tabelle. [du]": "sollst",
    "8c. Ergänzen Sie die Tabelle. [ihr]": "sollt",
    "8c. Ergänzen Sie die Tabelle. [sie/Sie]": "sollen",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [1]": "soll, bleiben",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [2]": "sollst, bewegen",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [3]": "sollen, kommen",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [4]": "soll, absagen",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [5]": "sollen, anrufen",
    "8d. Ergänzen Sie sollen und die Verben in den Sätzen. [6]": "sollt, sein",
    "8e. 2": "Er soll das Motorrad verkaufen.",
    "8e. 3": "Er soll nicht so schnell fahren.",
    "8e. 4": "Er soll mit dem Bus zur Arbeit fahren.",
    "8e. 5": "Er soll nicht viel zu Fuß gehen.",
    "10. Was sagt der Arzt und Patientin? [2]": "A",
    "10. Was sagt der Arzt und Patientin? [3]": "P",
    "10. Was sagt der Arzt und Patientin? [4]": "P",
    "10. Was sagt der Arzt und Patientin? [5]": "A",
    "10. Was sagt der Arzt und Patientin? [6]": "P",
    "10. Was sagt der Arzt und Patientin? [7]": "A",
    "10. Was sagt der Arzt und Patientin? [8]": "A",
    "10. Was sagt der Arzt und Patientin? [9]": "A",
    "10. Was sagt der Arzt und Patientin? [10]": "P",
    "10. Was sagt der Arzt und Patientin? [11]": "A",
    "10. Was sagt der Arzt und Patientin? [12]": "A",
    "10. Was sagt der Arzt und Patientin? [13]": "P",
    "10. Was sagt der Arzt und Patientin? [14]": "A",
    "10. Was sagt der Arzt und Patientin? [15]": "P",
    "10c. Was passt nicht? [1]": "3",
    "10c. Was passt nicht? [2]": "2",
    "10c. Was passt nicht? [3]": "1",
    "10c. Was passt nicht? [4]": "3",
    "10c. Was passt nicht? [5]": "4",
    "10e. Ergänzen Sie. [1]": "darf",
    "10e. Ergänzen Sie. [2]": "darf",
    "10e. Ergänzen Sie. [3]": "dürfen",
    "10e. Ergänzen Sie. [4]": "darfst",
    "10e. Ergänzen Sie. [5]": "darf",
    "10e. Ergänzen Sie. [6]": "dürft",
    "10e. Ergänzen Sie. [7]": "dürfen",
    "10f. Ergänzen Sie. [1]": "darf, nicht",
    "10f. Ergänzen Sie. [2]": "muss",
    "10f. Ergänzen Sie. [3]": "muss",
    "10f. Ergänzen Sie. [4]": "darf",
    "10f. Ergänzen Sie. [5]": "müssen",
    "10f. Ergänzen Sie. [6]": "dürfen, nicht",
    "10f. Ergänzen Sie. [7]": "muss",
    "10f. Ergänzen Sie. [8]": "darf",
    "11a. Ordnen Sie zu. [1]": "die Tabelle",
    "11a. Ordnen Sie zu. [2]": "die Salbe",
    "11a. Ordnen Sie zu. [3]": "der Saft",
    "11a. Ordnen Sie zu. [4]": "das Pflaster",
    "11a. Ordnen Sie zu. [5]": "der Verband",
    "11a. Ordnen Sie zu. [6]": "die Tropfen",
    "11a. Ordnen Sie zu. [7]": "die Spritze",
    "11b. Ordnen Sie zu. [1]": "nehmen",
    "11b. Ordnen Sie zu. [2]": "wechseln",
    "11b. Ordnen Sie zu. [3]": "geben und trinken",
    "11b. Ordnen Sie zu. [4]": "nehmen",
    "11b. Ordnen Sie zu. [5]": "bekommen",
    "13a. Komposita. [2]": "die, F",
    "13a. Komposita. [3]": "die, A",
    "13a. Komposita. [4]": "die, B",
    "13a. Komposita. [5]": "der, G",
    "13a. Komposita. [6]": "das, H",
    "13a. Komposita. [7]": "der, D",
    "13a. Komposita. [8]": "der, E",
    "13c. Kreuzen Sie an. [A]": "falsch",
    "13c. Kreuzen Sie an. [B]": "richtig",
    "1a. Was passt zusammen? [1]": "H",
    "1a. Was passt zusammen? [2]": "G",
    "1a. Was passt zusammen? [3]": "C",
    "1a. Was passt zusammen? [4]": "K",
    "1a. Was passt zusammen? [5]": "N",
    "1a. Was passt zusammen? [6]": "I",
    "1a. Was passt zusammen? [7]": "F",
    "1a. Was passt zusammen? [8]": "J",
    "1a. Was passt zusammen? [9]": "A",
    "1a. Was passt zusammen? [10]": "B",
    "1a. Was passt zusammen? [11]": "E",
    "1a. Was passt zusammen? [12]": "O",
    "1a. Was passt zusammen? [13]": "M",
    "1a. Was passt zusammen? [14]": "D",
    "1a. Was passt zusammen? [15]": "L",
    "1c. Wie heißen die Zimmer? [A]": "das, Badezimmer",
    "1c. Wie heißen die Zimmer? [B]": "das, Wohnzimmer",
    "1c. Wie heißen die Zimmer? [C]": "das, Schlafzimmer",
    "1c. Wie heißen die Zimmer? [D]": "das, Arbeitszimmer",
    "1c. Wie heißen die Zimmer? [E]": "das, Kinderzimmer",
    "2. Lesen Sie. [1]": "C",
    "2. Lesen Sie. [2]": "D",
    "2. Lesen Sie. [3]": "B",
    "2. Lesen Sie. [4]": "A",
    "3a. Wie ist die Wohnung? [1]": "billig",
    "3a. Wie ist die Wohnung? [2]": "klein",
    "3a. Wie ist die Wohnung? [3]": "hell",
    "3a. Wie ist die Wohnung? [4]": "ruhig",
    "3b. Lesen Sie. [1]": "3",
    "3b. Lesen Sie. [2]": "90",
    "3b. Lesen Sie. [3]": "850",
    "3b. Lesen Sie. [4]": "Nähe Bahnhof",
    "4a. Hören Sie. [Waschmaschine]": "Bad",
    "4a. Hören Sie. [Regale]": "Flur",
    "4a. Hören Sie. [Schrank]": "Wohnzimmer",
    "4a. Hören Sie. [Betten]": "Schlafzimmer",
    "4a. Hören Sie. [Esstisch]": "Küche",
    "4a. Hören Sie. [Sofa]": "Wohnzimmer",
    "4c. Kreuzen Sie an. [1]": "ins",
    "4c. Kreuzen Sie an. [2]": "in den",
    "4c. Kreuzen Sie an. [3]": "ins",
    "4c. Kreuzen Sie an. [4]": "in die",
    "4c. Kreuzen Sie an. [5]": "in die",
    "4c. Kreuzen Sie an. [6]": "ins",
    "5a. Hören Sie. [1]": "ja",
    "5a. Hören Sie. [2]": "ja",
    "5a. Hören Sie. [3]": "nein",
    "5a. Hören Sie. [4]": "ja",
    "5b. Sortieren Sie. [ihr]": "2",
    "5b. Sortieren Sie. [eine]": "4",
    "5b. Sortieren Sie. [also]": "5",
    "5b. Sortieren Sie. [vielen]": "3",
    "5b. Sortieren Sie. [liebe]": "1",
    "5b. Sortieren Sie. [danke]": "2",
    "5b. Sortieren Sie. [feiert]": "6",
    "5b. Sortieren Sie. [hallo]": "1",
    "5b. Sortieren Sie. [ich kann]": "3",
    "5b. Sortieren Sie. [aber]": "5",
    "5b. Sortieren Sie. [ich muss]": "4",
    "6a. Ergänzen Sie [1]": "auf",
    "6a. Ergänzen Sie [2]": "im",
    "6a. Ergänzen Sie [3]": "hinter",
    "6a. Ergänzen Sie [4]": "neben",
    "6a. Ergänzen Sie [5]": "vor",
    "6a. Ergänzen Sie [6]": "an",
    "6a. Ergänzen Sie [7]": "zwischen",
    "6a. Ergänzen Sie [8]": "über",
    "6a. Ergänzen Sie [9]": "unter",
    "6b. Hören Sie. [das Besteck]": "auf, der Tisch",
    "6b. Hören Sie. [die Gläser]": "über, die Tassen",
    "6b. Hören Sie. [die Flasche]": "hinter, das Sofa",
    "6b. Hören Sie. [die Servietten]": "unter, die Bücher",
    "8a. Kreuzen Sie an. [1]": "b",
    "8a. Kreuzen Sie an. [2]": "b",
    "8a. Kreuzen Sie an. [3]": "a",
    "8a. Kreuzen Sie an. [4]": "b",
    "8a. Kreuzen Sie an. [5]": "b",
    "8a. Kreuzen Sie an. [6]": "a",
    "9b. Hören Sie. [A]": "2",
    "9b. Hören Sie. [B]": "1",
    "9b. Hören Sie. [C]": "3",
    "12a. Lesen Sie. [Wählen Sie aus.]": "Wohnen, Geld, Freunde",
    "12b. Kreuzen Sie an. [2]": "falsch",
    "12b. Kreuzen Sie an. [3]": "richtig",
    "12b. Kreuzen Sie an. [4]": "richtig",
    "12b. Kreuzen Sie an. [5]": "falsch",
    "12b. Kreuzen Sie an. [6]": "richtig",
    "12b. Kreuzen Sie an. [7]": "falsch"
  }
};
